practice: # Configuration for the `practice` command
  count: 20               # Number of challenges for the session
  strict: false           # TODO: All characters must be written correctly before passing the challenge
  press_enter: true       # Do not advance to the next challenge until pressing enter
  repeat_failures: 5      # After finishing with all challenges, repeat failed challenges this amount of times
  record_failures: true   # TODO: Record failed challenges
