{
 "title": "Code Hanon Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors in 3-grams",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT ngram, value FROM ngrams WHERE status = \"KO\" ORDER BY value desc",
     "rawQueryText": "SELECT ngram, value FROM ngrams WHERE status = \"KO\" ORDER BY value desc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Latencies per 3-gram",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT ngram, AVG(value) as average_value, COUNT(value) as count FROM latencies group by ngram ORDER BY average_value desc\n",
     "rawQueryText": "SELECT ngram, AVG(value) as average_value, COUNT(value) as count FROM latencies group by ngram ORDER BY average_value desc\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Errors per expression",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "queryText": "SELECT expression, value FROM expressions WHERE status == \"KO\" ORDER BY value desc",
     "rawQueryText": "SELECT expression, value FROM expressions WHERE status == \"KO\" ORDER BY value desc",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}